
version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back-network:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME_DOCKERHUB}/${UI_VERSION}
    ports:
      - ${UI_PORT}
    networks:
      - front-network
    depends_on:
      - post
      - comment

  post:
    build: ./post-py
    image: ${USERNAME_DOCKERHUB}/post:2.0
    networks:
      - back-network
      - front-network
    depends_on:
      - post_db

  comment:
    build: ./comment
    image: ${USERNAME_DOCKERHUB}/comment:1.0
    networks:
      - back-network
      - front-network
    depends_on:
      - post_db

volumes:
  post_db:

networks:
  back-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
